"""add comfirmed record

Revision ID: 1ae51d4e6e1
Revises: None
Create Date: 2015-11-12 00:03:09.919821

"""

# revision identifiers, used by Alembic.
revision = '1ae51d4e6e1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
